; PlatformIO Project Configuration File (Phase 3 - Hardware Wiretap)

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
upload_port = D:
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_eol = CRLF