[platformio]
default_envs = uno, pico

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = bblanchon/ArduinoJson @ ^7.0.4
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_eol = CRLF

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_deps = bblanchon/ArduinoJson @ ^7.0.4
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_eol = CRLF
