[platformio]
default_envs = uno, pico, esp32

[env]
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3

[env:uno]
framework = arduino
platform = atmelavr
board = uno
build_flags = -D HAL_AVR
test_build_src = true
test_ignore = test_native

[env:pico]
framework = arduino
platform = raspberrypi
board = pico
build_flags = -D HAL_RP2040
test_build_src = true
test_ignore = test_native

[env:esp32]
framework = arduino
platform = espressif32
board = esp32dev
build_flags = -D HAL_ESP32
test_build_src = true
test_ignore = test_native

[env:native]
platform = native
build_flags = -std=c++11 -D HAL_NATIVE
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
test_build_src = true
